version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn paraphraser.wsgi -b 0.0.0.0:8000"
    volumes:
      - backend:/app
    ports:
      - 8000:8000
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - frontend:/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

volumes:
  backend:
  frontend:
