version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
  frontend:
    build: ./frontend
    command: yarn start
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

networks:
  default:
    driver: bridge